2023-07-21 12:01:33.809011: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\Bugs\069\original_code_snippet.py", line 23, in <module>
    enc(eg_input)
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\Bugs\069\original_code_snippet.py", line 17, in call
    x = self.attn_layer(query=x, key=x, value=x)  # Output: (4, 5, 20, 64)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer 'softmax' (type Softmax).

{{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4,5,2,20,20] vs. [4,5,1,5,20] [Op:AddV2] name: 

Call arguments received by layer 'softmax' (type Softmax):
  • inputs=tf.Tensor(shape=(4, 5, 2, 20, 20), dtype=float32)
  • mask=tf.Tensor(shape=(4, 5, 1, 5, 20), dtype=bool)
