2023-07-12 14:58:01.455026: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\Bugs\048\main.py", line 29, in <module>
    model = create_model()
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\Bugs\048\main.py", line 21, in create_model
    o = Multiply()([x, m]) #trying to multiply x with o. Doesn't work though!
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1751, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "multiply" (type Multiply).

dim 1 not in the interval [-1, 0]. for '{{node multiply/ExpandDims}} = ExpandDims[T=DT_INT32, Tdim=DT_INT32](multiply/ExpandDims/input, multiply/ExpandDims/dim)' with input shapes: [], [] and with computed input tensors: input[1] = <1>.

Call arguments received by layer "multiply" (type Multiply):
  • inputs=['tf.Tensor(shape=(None, 1), dtype=float32)', 'tf.Tensor(shape=(), dtype=int32)']
