2023-07-01 11:21:58.415273: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1/10

1/2 [==============>...............] - ETA: 0s - loss: 1.6080 - acc: 0.3750
2/2 [==============================] - 1s 12ms/step - loss: 1.6316 - acc: 0.2667
Epoch 2/10

1/2 [==============>...............] - ETA: 0s - loss: 1.5910 - acc: 0.3750
2/2 [==============================] - 0s 1ms/step - loss: 1.5770 - acc: 0.3333
Epoch 3/10

1/2 [==============>...............] - ETA: 0s - loss: 1.5359 - acc: 0.5000
2/2 [==============================] - 0s 40ms/step - loss: 1.5215 - acc: 0.6667
Epoch 4/10

1/2 [==============>...............] - ETA: 0s - loss: 1.4555 - acc: 0.7500
2/2 [==============================] - 0s 2ms/step - loss: 1.4764 - acc: 0.7333
Epoch 5/10

1/2 [==============>...............] - ETA: 0s - loss: 1.4051 - acc: 1.0000
2/2 [==============================] - 0s 120us/step - loss: 1.4298 - acc: 0.8667
Epoch 6/10

1/2 [==============>...............] - ETA: 0s - loss: 1.3797 - acc: 0.8750
2/2 [==============================] - 0s 4ms/step - loss: 1.3846 - acc: 0.8667
Epoch 7/10

1/2 [==============>...............] - ETA: 0s - loss: 1.3565 - acc: 0.8750
2/2 [==============================] - 0s 0s/step - loss: 1.3391 - acc: 0.9333
Epoch 8/10

1/2 [==============>...............] - ETA: 0s - loss: 1.3091 - acc: 1.0000
2/2 [==============================] - 0s 2ms/step - loss: 1.2940 - acc: 1.0000
Epoch 9/10

1/2 [==============>...............] - ETA: 0s - loss: 1.2969 - acc: 1.0000
2/2 [==============================] - 0s 8ms/step - loss: 1.2520 - acc: 1.0000
Epoch 10/10

1/2 [==============>...............] - ETA: 0s - loss: 1.2658 - acc: 1.0000
2/2 [==============================] - 0s 0s/step - loss: 1.2086 - acc: 1.0000
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='dense_input'), name='dense_input', description="created by layer 'dense_input'"), but it was called on an input with incompatible shape (1,).
Traceback (most recent call last):
  File "C:\Users\XYZ\Downloads\Bug Reproducibility\Bugs\007\main.py", line 30, in <module>
    predictions = model.predict(x_data[0])
  File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MEHILS~1\AppData\Local\Temp\__autograph_generated_fileubba308c.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\engine\training.py", line 2137, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\engine\training.py", line 2123, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\engine\training.py", line 2111, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\engine\training.py", line 2079, in predict_step
        return self(x, training=False)
    File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\XYZ\Downloads\Bug Reproducibility\venv\lib\site-packages\keras\engine\input_spec.py", line 250, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential' (type Sequential).
    
    Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (1,)
    
    Call arguments received by layer 'sequential' (type Sequential):
      � inputs=tf.Tensor(shape=(None,), dtype=float32)
      � training=False
      � mask=None

